#!/bin/bash

#Usage: stashcp [-d] -s <source> -l <location to be copied to>

debug=0
file=""
loc="."
while getopts ":ds:l:" opt; do
    case $opt in 
	d)
	    debug=2
	    ;;
	s)
	    source=$OPTARG
	    ;;
	l)
	    loc=$OPTARG
	    ;;
	\?)
	    echo "Invalid option: -$OPTARG" >&2
	    ;;
    esac
done

if [ $debug -eq 2 ]; then
	xrdargs="-d 2 -v"
else
	xrdargs="-s"
fi

#set prefix to proper format
myprefix=$(echo $STASHPREFIX | rev | cut -c 2- | rev)

if [ ${#myprefix} -lt 6 ]; then
    myprefix="root://data.ci-connect.net"
fi
if [ $debug -eq 2 ]; then
    echo "I think my STASHPREFIX is $STASHPREFIX"
    echo "I think my prefix is $myprefix"
fi

#try pulling from closest cache
#if xrdcp doesn't finish in 30 minutes, stop
#check to see if chosen path is a file or directory
isdir=$(xrdfs $myprefix stat $source | grep "IsDir" | wc -l)
if [ $isdir -eq 0 ]; then
	files=($source)
else
	files=$(xrdfs $myprefix ls $source)
	lc=$(echo "${source: -1}")
	if [ $lc == "/" ]; then
		dirname=$(echo $source | rev | cut -d/ -f2 | rev)
	else
		dirname=$(echo $source | rev | cut -d/ -f1 | rev)
	fi
	loc=$loc/$dirname
	mkdir -p $loc
fi

#pull here
for file in ${files[@]}; do
	fisdir=$(xrdfs $myprefix stat $file | grep "IsDir" | wc -l)
	if [ $fisdir -ne 0 ]; then
		if [ $debug -eq 2 ]; then
			fl="-d"
		else
			fl=""
		fi
		echo "stashcp $fl -s $file -l $loc"
		continue
	fi
	timeout 30m xrdcp $xrdargs -f $myprefix://$file $loc
	res=$?
	
	#check to see if the pull worked, and file exists and has non-zero size
	#if not, pull from trunk
	myfile=$(echo $file | rev | cut -d/ -f1 | rev)
	if [ $res -ne 0 ] || [ ! -s $loc/$myfile ]; then
		if [ $debug -eq 2 ]; then		
			echo "Pull from $myprefix failed."
			echo "Trying to pull from trunk."
		fi
		timeout 30m xrdcp $xrdargs -f root://data.ci-connect.net://$file $loc 2>&1
		res=$?
		if [ $res -ne 0 ] || [ ! -s $loc/$myfile ]; then				
			echo "Stashcp of $file failed."
		elif [ $debug -eq 2 ]; then
			echo "Pull from trunk was successful."
		fi
	elif [ $debug -eq 2 ]; then		
		echo "Pull of $myfile from $myprefix was successful."
	fi
done