#!/bin/bash
CACHE_FQDN=${CACHE_FQDN:-$(hostname -f)}
curl --silent --show-error --fail "https://topology.opensciencegrid.org/stashcache/authfile?cache_fqdn=${CACHE_FQDN}" > /run/stashcache-cache-server-auth/Authfile.tmp && \
mv /run/stashcache-cache-server-auth/Authfile.tmp /run/stashcache-cache-server-auth/Authfile
