#!/bin/bash
ORIGIN_FQDN=${ORIGIN_FQDN:-$(hostname -f)}
# -k needed to avoid error due to not having a client cert
curl -k --silent --show-error --fail "https://topology.opensciencegrid.org/stashcache/origin-authfile?fqdn=${ORIGIN_FQDN}" -o /run/stash-origin-auth/Authfile.tmp && \
mv /run/stash-origin-auth/Authfile.tmp /run/stash-origin-auth/Authfile
curl -k --silent --show-error --fail "https://topology.opensciencegrid.org/stashcache/origin-authfile-public?fqdn=${ORIGIN_FQDN}" -o /run/stash-origin/Authfile.tmp && \
mv /run/stash-origin/Authfile.tmp /run/stash-origin/Authfile

